version: "3"
services:
  nginx:
    image: nginx:1.29.1
    ports:
      - "81:80"
    volumes:
      - ./php-app:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  php-app:
    build:
      context: ./php-app
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    volumes:
      - ./php-app:/var/www/html:cached
      - php-app-storage:/var/www/html/storage
      - php-app-cache:/var/www/html/bootstrap/cache
      - /var/www/html/vendor
    expose:
      - "9000"
    user: "www-data"
    networks:
      - app-network

  nodejs-app:
    build:
      context: ./nodejs-app
      dockerfile: Dockerfile
    volumes:
      - ./nodejs-app:/usr/src/app
    expose:
      - "3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  php-app-storage:
  php-app-cache:
